### ISSUE TITLE
Edición Fehaciente

### ISSUE THREAD

**Issue by hspencer** [eadpucv/ead_personas#24]
<img width="770" alt="captura de pantalla 2017-06-15 a la s 09 48 01" src="https://user-images.githubusercontent.com/896632/27184293-c511aa9e-51af-11e7-99bb-0ecd62c0d8ab.png">
En la pantalla Edición de Usuario no indica qué usuario está editanto.
Sugiero poner un nuevo encabezado:

# Editar Usuario: **NombreDeUsuario**

**Comment by hspencer** [comment]
por favor actualizar esto

**Comment by kaosb** [comment]
![image](https://user-images.githubusercontent.com/1421478/28596820-bb6f0850-7168-11e7-9519-040d2d36a743.png)
