### ISSUE TITLE
Filtrar Exportar

### ISSUE THREAD

**Issue by hspencer** [eadpucv/ead_personas#26]
@kaosb Esta funcionalidad estaba en la versión anterior.
Para resolver la urgencia, te propongo 2 alternativas, la ideal y la rápida:

Para ambos casos se debe acceder a esta funcionalidad corresponde que esté en este menú
<img width="840" alt="captura de pantalla 2017-07-14 a la s 09 03 20" src="https://user-images.githubusercontent.com/896632/28213236-35c07ea8-6873-11e7-8d13-fd1c03e75ede.png"> 

1. La opción original consiste en un buscador avanzado que filtra varios campos
2. la opción rápida sería exportar un CSV o lo que sea de toda la BBDD con checkboxes por cabecera que se quiere incluir

¿te parece?

Respecto al diseño, el botón "nuevo usuario" en verde grande está malísimamente ubicado en la caja del buscador, además el comportamiento en pantallas pequeñas es horrible. Si se puede hacer algo con eso, bkn.

**Comment by kaosb** [comment]
@hspencer lo hago como quieres. pero.. mandame el front. o sea recuerda que yo no hice el front. y recuerda que mi guia fue el front que estaba en las plantillas. si bien recuerdo que lo hablamos era el ejemplo que tenia y por eso se hizo asi. y lo que no fue de mi cosecha pero recuerda que el front no es mio plz. mandame el front y lo hago como quieres.
